### ISSUE TITLE
Include more recent oneAPI versions

### ISSUE THREAD

**Issue by aradi** [rscohn2/setup-oneapi#35]
This GitHub action is really super useful, thanks for providing it.

Any plans to include also the most recent oneAPI release(s)?

**Comment by rscohn2** [comment]
> This GitHub action is really super useful, thanks for providing it.
> 
> Any plans to include also the most recent oneAPI release(s)?

Thanks for letting me know that it is useful.

I have  updated for the 2024.1 release.

**Comment by aradi** [comment]
Cool, thanks a lot!
