### ISSUE TITLE
Options for 2024.2 and 2025.0 releases

### ISSUE THREAD

**Issue by marcfehling** [rscohn2/setup-oneapi#47]
Thank you for providing this easy-to-use GitHub action to setup oneAPI resources.

Since your latest update in May, I noticed that Intel oneAPI has had two new releases, i.e., 2024.2 and 2025.0.

I wanted to kindly ask if it is possible to add these new releases to your GitHub action. Let me know if I can somehow support you. I will be happy to help with the right instructions.

**Comment by rscohn2** [comment]
I pubished an update. Let me know if it works. Please look over the README. I added some directions on how to do an update. You have to cut/paste installer URLS from spack.

**Comment by marcfehling** [comment]
Thank you for the update. So far it seems to work fine in the projects I'm using. Next time, I will prepare a patch myself following your README and #48.

I noticed that one of your CI jobs is failing: [compilers/Test MPI](https://github.com/rscohn2/setup-oneapi/actions/runs/11723729374/job/32656022908)
That is because `ifort` has been discontinued. I will prepare a patch.

**Comment by rscohn2** [comment]
Thanks for the PR's and offering to help with the updates!
